### ISSUE TITLE
[2020-09-23] weekly scrum

### ISSUE THREAD

**Issue by HyowonSin** [covid19-cau/capstone-design-project#14]
Development up to week 1
-~Proposal~
-~Research and Advancement of planning~

Development up to week 2
-~Research and Advancement of planning~
-Architect db
-Architect rest api server
-Architect client structure

Week 3 development goal according to the time schedule
-Architect db
-Architect rest api server
-Architect client structure

**Comment by Brew-Brew** [comment]
1ㅁㄴㅇㅁㅈㅂㅇㅁ

**Comment by Brew-Brew** [comment]
**What I did**
