### ISSUE TITLE
[2020-10-7] weekly scrum

### ISSUE THREAD

**Issue by Brew-Brew** [covid19-cau/capstone-design-project#31]
**Issue** 
- set DB server to aws and connect this server to spring boot server

**What Did**
- Hyowon
  - DB setup and architect db more advanced
  - insert data
- Keunwoo
  - develop api server & test data with local server and make connection to DB
- Seungkyu
  - DB server setup to aws (infra)
  - develop admin UI

**What should Do**
- Admin API server response check
- Dividing backend work (JPA, DAO integration)
- Check additionaly needed api

**Comment by gwkim9288** [comment]
-add modify and delete contents and user feature for admin

- produce local data and test rest api using Postman service.

![image](https://user-images.githubusercontent.com/64244688/95542858-ea915380-0a31-11eb-9bcb-6d0fea17250b.png)

![image](https://user-images.githubusercontent.com/64244688/95542907-0bf23f80-0a32-11eb-9877-7e89a0d7acf4.png)

[to do next week]

- implement jpa for using cloud data , not local data
- test rest api implemented, and link together frontend

**Comment by HyowonSin** [comment]
[This week]

* String-Boot JPA setting

* JPA-Database connection

* Entity class development

* Repository development

![image](https://user-images.githubusercontent.com/48724199/95580267-074d7b80-0a72-11eb-88bf-005ea8132c99.png)

![image](https://user-images.githubusercontent.com/48724199/95580508-6a3f1280-0a72-11eb-96ef-2e1b0eb6d846.png)


[After Plan]

* Patial test

* Layout classification (Application architecture)

* API development

* AWS connection test
