### ISSUE TITLE
[2020-10-14] Weekly scrum

### ISSUE THREAD

**Issue by Brew-Brew** [covid19-cau/capstone-design-project#58]
**Issue** 
- none

**What Did**
- Hyowon
  - DB setup with jpa
- Keunwoo
  - api swagger
  - delete, update api feature
  - main page api setting for user
  - user auth module
- Seungkyu
  - develop admin UI
    - update recommend contents
    - delete reecommend contents

**What should Do**
- user's challenge info mapping

**Comment by Brew-Brew** [comment]
**What I did**
- admin rocemmend contents delete api maaping
  - https://github.com/covid19-cau/capstone-design-project/pull/54
- admin recommend contents update api mapping 
  - https://github.com/covid19-cau/capstone-design-project/pull/52

**Comment by HyowonSin** [comment]
* Table Mapping ( RDBS Foreign Key - JPA MappedBy(Reference))

** Plan

![image](https://user-images.githubusercontent.com/48724199/97079143-9343d380-162c-11eb-81af-cc5f32bb2e9f.png)

** Mapping

![image](https://user-images.githubusercontent.com/48724199/97079214-136a3900-162d-11eb-8043-ecf0f2178633.png)

![image](https://user-images.githubusercontent.com/48724199/97079217-182eed00-162d-11eb-8020-6a51703f2fc2.png)

![image](https://user-images.githubusercontent.com/48724199/97079219-1a914700-162d-11eb-95dc-be39dda02d1d.png)

![image](https://user-images.githubusercontent.com/48724199/97079221-1d8c3780-162d-11eb-957d-47141997f48d.png)
