### ISSUE TITLE
[2020-11-4] Weekly Scrum

### ISSUE THREAD

**Issue by Brew-Brew** [covid19-cau/capstone-design-project#68]

**Comment by Brew-Brew** [comment]
**What I did** (status 100%)
- add signin, signup UI of user page
- add font style
  - https://github.com/covid19-cau/capstone-design-project/pull/67

**What i will**
- api integration of user signin , signup api
- main page ui supplement

**Comment by gwkim9288** [comment]
- implement authentication feature using jwt token , and using algorithm HS256.
- login and singup api developed,and add security to other api (/admin/** : only for admin, /user/**: for user)

(login test using postman get token through reponse body)
![image](https://user-images.githubusercontent.com/64244688/98430034-039f2a00-20ee-11eb-943c-cfd134799aef.png)

(when using admin api, put token to header )
![image](https://user-images.githubusercontent.com/64244688/98430050-20d3f880-20ee-11eb-984d-5886cb9158b4.png)

![image](https://user-images.githubusercontent.com/64244688/98430074-52e55a80-20ee-11eb-9dac-900a85ce9ccb.png)

![image](https://user-images.githubusercontent.com/64244688/98430078-5aa4ff00-20ee-11eb-91ad-ba97089a04aa.png)

What i will

- if there is error in authentication, error correcting
- develop rest api for main page
