### ISSUE TITLE
[2020-11-11] Weekly Scrum

### ISSUE THREAD

**Issue by Brew-Brew** [covid19-cau/capstone-design-project#74]

**Comment by Brew-Brew** [comment]
**What I did** (status 100%)
- add login and signup api integration
- get thumbnail from youtube video and edit main page ui
  - https://github.com/covid19-cau/capstone-design-project/pull/72
  - https://github.com/covid19-cau/capstone-design-project/pull/73
![image](https://user-images.githubusercontent.com/26598542/98958058-3b223200-2545-11eb-9c68-71bb1d7915a9.png)

![스크린샷 2020-11-04 오전 12 18 53](https://user-images.githubusercontent.com/26598542/98004757-a4ae8c00-1e33-11eb-8654-4054e5822d76.png)
![스크린샷 2020-11-04 오전 12 19 27](https://user-images.githubusercontent.com/26598542/98004761-a5dfb900-1e33-11eb-98c0-d5f5ac8555c6.png)


**What i will**
- main page ui supplement
- ui develop of challenge page

**Comment by gwkim9288** [comment]
this week my work:
- logout implementation
- user information get api in user page
-challenge get/create/check feature develop (..ing)

![image](https://user-images.githubusercontent.com/64244688/99143867-5eafbe80-26a4-11eb-838f-e1bbedcf1ebb.png)
![image](https://user-images.githubusercontent.com/64244688/99143872-65d6cc80-26a4-11eb-9af6-f80c28d249e4.png)
![image](https://user-images.githubusercontent.com/64244688/99143879-6ff8cb00-26a4-11eb-9d5e-c487e5f291c0.png)
![image](https://user-images.githubusercontent.com/64244688/99143882-78e99c80-26a4-11eb-976c-a9af58dfee22.png)

What i will
- test challenge api and error correcting
